services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: ["npm", "run", "dev"]
    ports:
      - "4000:4000"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - ./src/:/opt/app/src
      - ~/.aws/monum/dev_credentials:/home/node/.aws/credentials:ro
      - ~/.aws/monum/dev_config:/home/node/.aws/config:ro
    env_file: .env
    healthcheck:
      disable: true  
    depends_on:
      mongo:
        condition: service_healthy
  
  mongo:
    image: mongo:6
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=test
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: "[ `echo 'db.runCommand(\"ping\").ok' | mongo localhost/test --quiet` ] && echo 0 || echo 1"
      interval: 5s
      start_period: 10s
      timeout: 4s
      retries: 3

volumes:
  mongo_data: